name: Flutter CI (test & build)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
jobs:
  Tests-and-build-ubuntu-and-window:
    name: Tests and Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - run: flutter pub get
      - name: Create .env file
        run: |
          echo "KAKAO_NATIVE_APP_KEY=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "APPLE_REDIRECT_URI=${{ secrets.APPLE_REDIRECT_URI }}" >> .env
          echo "KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}" >> .env
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env
          cat .env
      - name: Create google-services.json file
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" >> android/app/google-services.json
      - name: add kakao key to local.properties file at Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo -e "\nkakao.sdk.appkey=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> android/local.properties
          cat android/local.properties
      - name: add kakao key to local.properties file at Window
        if: matrix.os == 'windows-latest'
        run: |
          "`nkakao.sdk.appkey=***" | Out-File -Append -FilePath "android/local.properties"
          cat android/local.properties
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

  Tests-and-build-macos:
    name: Tests and Build on MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
        architecture: x64
    - name: Create .env file
      run: |
        echo "KAKAO_NATIVE_APP_KEY=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> .env
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
        echo "APPLE_REDIRECT_URI=${{ secrets.APPLE_REDIRECT_URI }}" >> .env
        echo "KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}" >> .env
        echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env
        cat .env
    - name: Create Info.plist file
      run: |
        echo "${{ secrets.INFO_PLIST }}" >> ios/Runner/Info.plist
        cat ios/Runner/Info.plist
    - name: Create GoogleServices-Info.plist file
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_INFO_PLIST }}" >> ios/Runner/GoogleService-Info.plist
        cat ios/Runner/GoogleService-Info.plist
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign
