name: Flutter CI (test & build)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
jobs:
  Tests-and-build-ubuntu-and-window:
    name: Tests and Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.INFO_PLIST }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
